repos:
  - repo: https://github.com/aydabd/pre-commit-hook-registry
    rev: 416dfadef72f3dda87618b9284a208f02504b9d0 # v0.1.0
    hooks:
      - id: validate-registry-config
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: gitleaks
      - id: ruff-check
      - id: ruff-format
